#!/usr/bin/env bash
set -xeuo pipefail

DOMAIN=${1:-${DOMAIN:-science}}
RL_DIR=${RL_DIR:-/mnt/petrelfs/linjuekai/Multimodel_Reasoning/rl}
RL_DATA_DIR=${RL_DATA_DIR:-/mnt/petrelfs/linjuekai/Multimodel_Reasoning/rl_data/new_rl_data}

case "${DOMAIN}" in
    science) TRAIN_FILE=${TRAIN_FILE:-${RL_DATA_DIR}/train_science.parquet} ;;
    chart_table_doc) TRAIN_FILE=${TRAIN_FILE:-${RL_DATA_DIR}/train_chart_table_doc.parquet} ;;
    math) TRAIN_FILE=${TRAIN_FILE:-${RL_DATA_DIR}/train_math.parquet} ;;
    logic_game_puzzle) TRAIN_FILE=${TRAIN_FILE:-${RL_DATA_DIR}/train_logic_game_puzzle.parquet} ;;
    spatial_general) TRAIN_FILE=${TRAIN_FILE:-${RL_DATA_DIR}/train_spatial_general.parquet} ;;
    *) echo "Unknown DOMAIN=${DOMAIN}" >&2; exit 2 ;;
esac
export TRAIN_FILE
export VAL_FILE=${VAL_FILE:-${TRAIN_FILE}}

export EXPERIMENT_NAME=${EXPERIMENT_NAME:-qwen35_4b_full_sft_${DOMAIN}_gspo_qwen_judge}
export CKPTS_DIR=${CKPTS_DIR:-/mnt/dhwfile/raise/user/linjuekai/Multimodel_Reasoning/training/rl/${EXPERIMENT_NAME}}
export TOTAL_EPOCHS=${TOTAL_EPOCHS:-4}
export WARMUP_STEPS=${WARMUP_STEPS:-20}
export TRAIN_NCCL_TIMEOUT=${TRAIN_NCCL_TIMEOUT:-5400}
export REWARD_FUNCTION_PATH=${REWARD_FUNCTION_PATH:-${RL_DIR}/qwen_judge_reward.py}
export REWARD_FUNCTION_NAME=${REWARD_FUNCTION_NAME:-compute_score}
export CORRECTNESS_WEIGHT=${CORRECTNESS_WEIGHT:-1.0}
export FORMAT_WEIGHT=${FORMAT_WEIGHT:-0.0}

export URL_FILE=${URL_FILE:-${RL_DIR}/qwen_judge_urls/${DOMAIN}_${SLURM_JOB_ID:-manual}.txt}
export SERVE_VERIFIER_SCRIPT=${SERVE_VERIFIER_SCRIPT:-${RL_DIR}/serve_qwen_judge.sh}
export VERIFIER_LOG_PREFIX=${VERIFIER_LOG_PREFIX:-serve_qwen_judge}

export COMPASS_VERIFIER_MODEL=${COMPASS_VERIFIER_MODEL:-qwen3.5-27b-judge}
export COMPASS_VERIFIER_TIMEOUT=${COMPASS_VERIFIER_TIMEOUT:-300}
export COMPASS_VERIFIER_TOKENIZER_PATH=${COMPASS_VERIFIER_TOKENIZER_PATH:-/mnt/dhwfile/raise/user/linjuekai/models/Qwen3.5-27B}
export COMPASS_VERIFIER_MAX_TOKENS=${COMPASS_VERIFIER_MAX_TOKENS:-1024}
export COMPASS_VERIFIER_INPUT_MAX_TOKENS=${COMPASS_VERIFIER_INPUT_MAX_TOKENS:-30000}
export COMPASS_CANDIDATE_TAIL_TOKENS=${COMPASS_CANDIDATE_TAIL_TOKENS:-30000}
export COMPASS_CANDIDATE_MAX_CHARS=${COMPASS_CANDIDATE_MAX_CHARS:-120000}
export COMPASS_CANDIDATE_FALLBACK_CHARS=${COMPASS_CANDIDATE_FALLBACK_CHARS:-60000}

export QWEN_JUDGE_MODEL=${QWEN_JUDGE_MODEL:-${COMPASS_VERIFIER_MODEL}}
export QWEN_JUDGE_TOKENIZER_PATH=${QWEN_JUDGE_TOKENIZER_PATH:-${COMPASS_VERIFIER_TOKENIZER_PATH}}
export QWEN_JUDGE_TEMPERATURE=${QWEN_JUDGE_TEMPERATURE:-0.1}
export QWEN_JUDGE_TOP_P=${QWEN_JUDGE_TOP_P:-1.0}
export QWEN_JUDGE_MAX_TOKENS=${QWEN_JUDGE_MAX_TOKENS:-${COMPASS_VERIFIER_MAX_TOKENS}}
export QWEN_JUDGE_RETRIES=${QWEN_JUDGE_RETRIES:-2}
export QWEN_JUDGE_INPUT_MAX_TOKENS=${QWEN_JUDGE_INPUT_MAX_TOKENS:-${COMPASS_VERIFIER_INPUT_MAX_TOKENS}}
export QWEN_JUDGE_CANDIDATE_TAIL_TOKENS=${QWEN_JUDGE_CANDIDATE_TAIL_TOKENS:-${COMPASS_CANDIDATE_TAIL_TOKENS}}
export QWEN_JUDGE_CANDIDATE_MAX_CHARS=${QWEN_JUDGE_CANDIDATE_MAX_CHARS:-${COMPASS_CANDIDATE_MAX_CHARS}}
export QWEN_JUDGE_CANDIDATE_FALLBACK_CHARS=${QWEN_JUDGE_CANDIDATE_FALLBACK_CHARS:-${COMPASS_CANDIDATE_FALLBACK_CHARS}}

bash "${RL_DIR}/run_gspo_compass_domain.sh" "${DOMAIN}"
